title = "Words"
baseurl = "https://words.tjp.io/"
languageCode = "en-us"

theme = "beautifulhugo"
PygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
  logo = "img/profile.png"
  bigimg = "/img/bigimg.jpg"
  subtitle = "by Travis Parker"

[Author]
  name = "Travis Parker"
  email = "travis.parker@gmail.com"
  facebook = "teepark84"
  github = "teepark"
  twitter = "teepark"
  linkedin = "in/travis-parker-252b00"
